apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-api
  template:
    metadata:
      labels:
        app: insurance-api
    spec:
      containers:
      - name: insurance-api
        image: your-dockerhub-username/insurance-api:latest
        ports:
        - containerPort: 8000